# Generated by Django 5.0.7 on 2024-09-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (4, 'Loan Paid'), (5, 'Money Transfer'), (2, 'Withdrawal'), (3, 'Loan')], null=True),
        ),
    ]
