# Generated by Django 5.0.7 on 2024-09-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_no',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(4, 'Loan Paid'), (2, 'Withdrawal'), (1, 'Deposit'), (5, 'Money Transfer'), (3, 'Loan')], null=True),
        ),
    ]
